package com.team1.slaintehealthinsurance;

import java.text.NumberFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author Cúán
 */
public class BuyPolicyPopup extends javax.swing.JFrame {

    ImageIcon image = new ImageIcon("src\\main\\java\\images\\icon.png");

    public BuyPolicyPopup(Customer customer, Policy policy) {
        initComponents();
        clearInfo();
        fillInfo(customer, policy);
    }

    //Clears label fields with information inputted on last screen
    private void clearInfo() {
        firstNameSummaryBox.setText(null);
        lastNameSummaryBox.setText(null);
        genderSummaryBox.setText(null);
        ageSummaryBox.setText(null);
        policyTypeSummaryBox.setText(null);
        hospitalCoverSummaryBox.setText(null);
        dayToDayExpensesSummaryBox.setText(null);
        existingHealthConditionSummaryBox.setText(null);
        otherSummaryBox.setText(null);
        smokerSummaryBox.setText(null);
        idNumberSummaryBox.setText(null);
    }

    //Populates label fields with information inputted on last screen
    private void fillInfo(Customer customer, Policy policy) {

        NumberFormat cf = NumberFormat.getCurrencyInstance();
        firstNameSummaryBox.setText(customer.getFirstName());
        lastNameSummaryBox.setText(customer.getLastName());
        genderSummaryBox.setText(customer.getGender());
        ageSummaryBox.setText(customer.getAge());
        policyTypeSummaryBox.setText(policy.getPolicyType());
        hospitalCoverSummaryBox.setText(policy.getHospitalCover());
        dayToDayExpensesSummaryBox.setText(policy.getDayToDayExpenses());
        otherSummaryBox.setText(customer.getOther());
        smokerSummaryBox.setText(customer.getSmokerStatus());
        idNumberSummaryBox.setText(policy.getFormattedNumber());

        //For loop to take out data from array list 
        for (Object existingHealthCondition : customer.getExistingHealthCondition()) {
            existingHealthConditionSummaryBox.append((String) existingHealthCondition + "\n");
        }

        totalSummaryBox.setText(String.valueOf(cf.format(policy.getTotal())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        healthInsuranceSummary = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        personalDetailsSummary = new javax.swing.JPanel();
        firstNameSummaryHeading = new javax.swing.JLabel();
        firstNameSummaryBox = new javax.swing.JLabel();
        lastNameSummaryHeading = new javax.swing.JLabel();
        ageSummaryHeading = new javax.swing.JLabel();
        ageSummaryBox = new javax.swing.JLabel();
        genderSummaryHeading = new javax.swing.JLabel();
        genderSummaryBox = new javax.swing.JLabel();
        lastNameSummaryBox = new javax.swing.JLabel();
        schemaDetailsSummary = new javax.swing.JPanel();
        policyTypeSummaryHeading = new javax.swing.JLabel();
        hospitalCoverSummaryHeading = new javax.swing.JLabel();
        dayToDayExpensesSummaryHeading = new javax.swing.JLabel();
        policyTypeSummaryBox = new javax.swing.JLabel();
        hospitalCoverSummaryBox = new javax.swing.JLabel();
        dayToDayExpensesSummaryBox = new javax.swing.JLabel();
        healthDetailsSummary = new javax.swing.JPanel();
        existingHealthConditionsSummaryHeading = new javax.swing.JLabel();
        smokerSummaryBox = new javax.swing.JLabel();
        otherSummaryHeading = new javax.swing.JLabel();
        smokeSummaryHeading = new javax.swing.JLabel();
        otherSummaryBox = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        existingHealthConditionSummaryBox = new javax.swing.JTextArea();
        finalQuotationSummary = new javax.swing.JPanel();
        totalSummaryHeading = new javax.swing.JLabel();
        totalSummaryBox = new javax.swing.JLabel();
        idNumberSummaryHeading = new javax.swing.JLabel();
        idNumberSummaryBox = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        formHeading = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sláinte Health Insurance");
        setIconImage(image.getImage());
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        healthInsuranceSummary.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quote Summary");

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        personalDetailsSummary.setBackground(new java.awt.Color(255, 255, 255));

        firstNameSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        firstNameSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        firstNameSummaryHeading.setText("First Name:");

        firstNameSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        firstNameSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        lastNameSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lastNameSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        lastNameSummaryHeading.setText("Last Name:");

        ageSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        ageSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        ageSummaryHeading.setText("Age:");

        ageSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        ageSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        genderSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        genderSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        genderSummaryHeading.setText("Gender:");

        genderSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        genderSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        lastNameSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lastNameSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout personalDetailsSummaryLayout = new javax.swing.GroupLayout(personalDetailsSummary);
        personalDetailsSummary.setLayout(personalDetailsSummaryLayout);
        personalDetailsSummaryLayout.setHorizontalGroup(
            personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsSummaryLayout.createSequentialGroup()
                .addGroup(personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameSummaryHeading)
                    .addComponent(lastNameSummaryHeading)
                    .addComponent(ageSummaryHeading)
                    .addComponent(genderSummaryHeading))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsSummaryLayout.createSequentialGroup()
                        .addComponent(genderSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(personalDetailsSummaryLayout.createSequentialGroup()
                        .addGroup(personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        personalDetailsSummaryLayout.setVerticalGroup(
            personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsSummaryLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailsSummaryLayout.createSequentialGroup()
                        .addComponent(firstNameSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genderSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalDetailsSummaryLayout.createSequentialGroup()
                        .addComponent(firstNameSummaryHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameSummaryHeading)
                        .addGap(18, 18, 18)
                        .addComponent(genderSummaryHeading)))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageSummaryHeading, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ageSummaryBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        schemaDetailsSummary.setBackground(new java.awt.Color(255, 255, 255));

        policyTypeSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        policyTypeSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        policyTypeSummaryHeading.setText("Policy Type:");

        hospitalCoverSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        hospitalCoverSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        hospitalCoverSummaryHeading.setText("Hospital Cover:");

        dayToDayExpensesSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        dayToDayExpensesSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        dayToDayExpensesSummaryHeading.setText("Day to Day Expenses:");

        policyTypeSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        policyTypeSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        hospitalCoverSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        hospitalCoverSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        dayToDayExpensesSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        dayToDayExpensesSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout schemaDetailsSummaryLayout = new javax.swing.GroupLayout(schemaDetailsSummary);
        schemaDetailsSummary.setLayout(schemaDetailsSummaryLayout);
        schemaDetailsSummaryLayout.setHorizontalGroup(
            schemaDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaDetailsSummaryLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(schemaDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayToDayExpensesSummaryHeading)
                    .addComponent(hospitalCoverSummaryHeading)
                    .addComponent(policyTypeSummaryHeading))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(schemaDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hospitalCoverSummaryBox, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(dayToDayExpensesSummaryBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(policyTypeSummaryBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        schemaDetailsSummaryLayout.setVerticalGroup(
            schemaDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaDetailsSummaryLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(schemaDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(schemaDetailsSummaryLayout.createSequentialGroup()
                        .addComponent(policyTypeSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalCoverSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dayToDayExpensesSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(schemaDetailsSummaryLayout.createSequentialGroup()
                        .addComponent(policyTypeSummaryHeading)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalCoverSummaryHeading)
                        .addGap(18, 18, 18)
                        .addComponent(dayToDayExpensesSummaryHeading)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        healthDetailsSummary.setBackground(new java.awt.Color(255, 255, 255));

        existingHealthConditionsSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        existingHealthConditionsSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        existingHealthConditionsSummaryHeading.setText("Existing Health Condition:");

        smokerSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        smokerSummaryBox.setForeground(new java.awt.Color(0, 0, 0));
        smokerSummaryBox.setPreferredSize(new java.awt.Dimension(103, 25));

        otherSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        otherSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        otherSummaryHeading.setText("Other:");

        smokeSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        smokeSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        smokeSummaryHeading.setText("Smoker:");

        otherSummaryBox.setEditable(false);
        otherSummaryBox.setBackground(new java.awt.Color(255, 255, 255));
        otherSummaryBox.setColumns(20);
        otherSummaryBox.setForeground(new java.awt.Color(0, 0, 0));
        otherSummaryBox.setRows(5);
        otherSummaryBox.setFocusable(false);

        existingHealthConditionSummaryBox.setEditable(false);
        existingHealthConditionSummaryBox.setBackground(new java.awt.Color(255, 255, 255));
        existingHealthConditionSummaryBox.setColumns(20);
        existingHealthConditionSummaryBox.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        existingHealthConditionSummaryBox.setForeground(new java.awt.Color(0, 0, 0));
        existingHealthConditionSummaryBox.setRows(5);
        existingHealthConditionSummaryBox.setFocusable(false);
        jScrollPane1.setViewportView(existingHealthConditionSummaryBox);

        javax.swing.GroupLayout healthDetailsSummaryLayout = new javax.swing.GroupLayout(healthDetailsSummary);
        healthDetailsSummary.setLayout(healthDetailsSummaryLayout);
        healthDetailsSummaryLayout.setHorizontalGroup(
            healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthDetailsSummaryLayout.createSequentialGroup()
                .addGroup(healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(healthDetailsSummaryLayout.createSequentialGroup()
                        .addComponent(existingHealthConditionsSummaryHeading)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(healthDetailsSummaryLayout.createSequentialGroup()
                        .addGroup(healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smokeSummaryHeading)
                            .addComponent(otherSummaryHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(163, 163, 163)
                        .addGroup(healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otherSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smokerSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        healthDetailsSummaryLayout.setVerticalGroup(
            healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthDetailsSummaryLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(existingHealthConditionsSummaryHeading)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherSummaryHeading))
                .addGap(18, 18, 18)
                .addGroup(healthDetailsSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smokeSummaryHeading)
                    .addComponent(smokerSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        finalQuotationSummary.setBackground(new java.awt.Color(255, 255, 255));

        totalSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        totalSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        totalSummaryHeading.setText("Total:");

        totalSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        totalSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        idNumberSummaryHeading.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        idNumberSummaryHeading.setForeground(new java.awt.Color(0, 0, 0));
        idNumberSummaryHeading.setText("ID Number:");

        idNumberSummaryBox.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        idNumberSummaryBox.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout finalQuotationSummaryLayout = new javax.swing.GroupLayout(finalQuotationSummary);
        finalQuotationSummary.setLayout(finalQuotationSummaryLayout);
        finalQuotationSummaryLayout.setHorizontalGroup(
            finalQuotationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalQuotationSummaryLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(idNumberSummaryHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idNumberSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(totalSummaryHeading)
                .addGap(18, 18, 18)
                .addComponent(totalSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        finalQuotationSummaryLayout.setVerticalGroup(
            finalQuotationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalQuotationSummaryLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(finalQuotationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idNumberSummaryHeading)
                    .addComponent(idNumberSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSummaryHeading)
                    .addComponent(totalSummaryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout healthInsuranceSummaryLayout = new javax.swing.GroupLayout(healthInsuranceSummary);
        healthInsuranceSummary.setLayout(healthInsuranceSummaryLayout);
        healthInsuranceSummaryLayout.setHorizontalGroup(
            healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthInsuranceSummaryLayout.createSequentialGroup()
                .addGroup(healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(healthInsuranceSummaryLayout.createSequentialGroup()
                        .addGroup(healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(schemaDetailsSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personalDetailsSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(finalQuotationSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(healthDetailsSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(healthInsuranceSummaryLayout.createSequentialGroup()
                        .addGroup(healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        healthInsuranceSummaryLayout.setVerticalGroup(
            healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthInsuranceSummaryLayout.createSequentialGroup()
                .addGroup(healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(healthInsuranceSummaryLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(healthInsuranceSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(healthInsuranceSummaryLayout.createSequentialGroup()
                        .addComponent(personalDetailsSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(schemaDetailsSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(healthDetailsSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(finalQuotationSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(image);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 150));

        formHeading.setBackground(new java.awt.Color(255, 255, 255));
        formHeading.setFont(new java.awt.Font("Calibri", 1, 50)); // NOI18N
        formHeading.setForeground(new java.awt.Color(255, 255, 255));
        formHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formHeading.setText("Sláinte Health Insurance");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(formHeading)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(formHeading)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(healthInsuranceSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(healthInsuranceSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyPolicyPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyPolicyPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyPolicyPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyPolicyPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new BuyPolicyPopup(customer).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageSummaryBox;
    private javax.swing.JLabel ageSummaryHeading;
    private javax.swing.JLabel dayToDayExpensesSummaryBox;
    private javax.swing.JLabel dayToDayExpensesSummaryHeading;
    private javax.swing.JTextArea existingHealthConditionSummaryBox;
    private javax.swing.JLabel existingHealthConditionsSummaryHeading;
    private javax.swing.JPanel finalQuotationSummary;
    private javax.swing.JLabel firstNameSummaryBox;
    private javax.swing.JLabel firstNameSummaryHeading;
    private javax.swing.JLabel formHeading;
    private javax.swing.JLabel genderSummaryBox;
    private javax.swing.JLabel genderSummaryHeading;
    private javax.swing.JPanel healthDetailsSummary;
    private javax.swing.JPanel healthInsuranceSummary;
    private javax.swing.JLabel hospitalCoverSummaryBox;
    private javax.swing.JLabel hospitalCoverSummaryHeading;
    private javax.swing.JLabel idNumberSummaryBox;
    private javax.swing.JLabel idNumberSummaryHeading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lastNameSummaryBox;
    private javax.swing.JLabel lastNameSummaryHeading;
    private javax.swing.JTextArea otherSummaryBox;
    private javax.swing.JLabel otherSummaryHeading;
    private javax.swing.JPanel personalDetailsSummary;
    private javax.swing.JLabel policyTypeSummaryBox;
    private javax.swing.JLabel policyTypeSummaryHeading;
    private javax.swing.JPanel schemaDetailsSummary;
    private javax.swing.JLabel smokeSummaryHeading;
    private javax.swing.JLabel smokerSummaryBox;
    private javax.swing.JLabel totalSummaryBox;
    private javax.swing.JLabel totalSummaryHeading;
    // End of variables declaration//GEN-END:variables
}
