package com.team1.slaintehealthinsurance;

import java.awt.Component;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cúán
 */
public class SláinteHealthInsurance extends javax.swing.JFrame {

    //Instance Variables
    private Customer customer;
    private Policy policy;
    private NumberFormat cf;
    private String firstName = "";
    private String lastName = "";
    private String gender = "";
    private String age = "";
    private String policyType = "";
    private String hospitalCover = "";
    private String dayToDayExpenses = "";
    private ArrayList<String> existingHealthCondition = new ArrayList<>();
    private final ImageIcon image = new ImageIcon("src\\main\\java\\images\\icon.png");
    private String other = "";
    private String smokerStatus = "";
    private String formattedNumber = "0001";
    private int idNumber = Integer.parseInt(formattedNumber);

    //Assume form is not completed at start of program - global variable accessed by all parts of the class
    static boolean formValidated = false;

    //Clear's all fields in the form
    private void clearFields() {
        firstNameTextbox.setText(null);
        lastNameTextbox.setText(null);
        genderButtonGroup.clearSelection();
        ageComboBox.setSelectedIndex(0);
        policyTypeComboBox.setSelectedIndex(0);
        hospitalCoverComboBox.setSelectedIndex(0);
        dayToDayExpensesComboBox.setSelectedIndex(0);
        existingHealthConditionList.setSelectedIndex(0);
        otherTextbox.setText("");
        smokerButtonGroup.clearSelection();
        displayTotalLabel.setText(null);
        calculateButton.setEnabled(true);
        buyPolicyButton.setEnabled(true);
        idNumber++;
        formattedNumber = String.format("%0" + formattedNumber.length() + "d", idNumber);
        policy.setFormattedNumber(formattedNumber);
        displayIdNumberLabel.setText(policy.getFormattedNumber());
    }

    //Method to Validate Form 
    private void validateForm() {
        //Checks if first name is not filled in if not selected -> prompt user to fill in first name 
        if (firstNameTextbox.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Please input first name",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (lastNameTextbox.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Please input last name",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (genderButtonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a gender",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (ageComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select an age",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (policyTypeComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a policy type",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (hospitalCoverComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a hospital cover",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (dayToDayExpensesComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select a day to daye expenses type",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (existingHealthConditionList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please select an option from the existing health conditions list",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else if (smokerButtonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(this,
                    "Please idicate whether or not you are a smoker",
                    "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            // Asumme form completed correctly 
            formValidated = true;
        }
    } //end validate form method

    /**
     * Creates new form SláinteHealthInsurance GUI
     */
    public SláinteHealthInsurance() {
        initComponents();
        clearFormButton.setEnabled(false);
        buyPolicyButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        smokerButtonGroup = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        formHeading = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        healthInsuranceForm = new javax.swing.JPanel();
        personalDetails = new javax.swing.JPanel();
        headingPersonalDetails = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextbox = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextbox = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        ageLabel = new javax.swing.JLabel();
        ageComboBox = new javax.swing.JComboBox<>();
        schemaDetails = new javax.swing.JPanel();
        headingSchemaDetails = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        policyTypeLabel = new javax.swing.JLabel();
        policyTypeComboBox = new javax.swing.JComboBox<>();
        hospitalCoverLabel = new javax.swing.JLabel();
        hospitalCoverComboBox = new javax.swing.JComboBox<>();
        dayToDayExpensesLabel = new javax.swing.JLabel();
        dayToDayExpensesComboBox = new javax.swing.JComboBox<>();
        finalQuotation = new javax.swing.JPanel();
        headingFinalQuotation = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        idNumberLabel = new javax.swing.JLabel();
        displayIdNumberLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        displayTotalLabel = new javax.swing.JLabel();
        finalButtons = new javax.swing.JPanel();
        calculateButton = new javax.swing.JButton();
        clearFormButton = new javax.swing.JButton();
        buyPolicyButton = new javax.swing.JButton();
        healthDetails = new javax.swing.JPanel();
        healthlDetails = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        existingHealthConditionLabel = new javax.swing.JLabel();
        existingHealthConditionList = new javax.swing.JList<>();
        otherLabel = new javax.swing.JLabel();
        otherScrollPane = new javax.swing.JScrollPane();
        otherTextbox = new javax.swing.JTextArea();
        smokerLabel = new javax.swing.JLabel();
        smokerRadio = new javax.swing.JRadioButton();
        nonSmokerRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sláinte Health Insurance");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(image.getImage());
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1200, 800));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(image);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 150));

        formHeading.setBackground(new java.awt.Color(255, 255, 255));
        formHeading.setFont(new java.awt.Font("Calibri", 1, 50)); // NOI18N
        formHeading.setForeground(new java.awt.Color(255, 255, 255));
        formHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formHeading.setText("Sláinte Health Insurance");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(formHeading)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(formHeading)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1210, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        healthInsuranceForm.setBackground(new java.awt.Color(255, 255, 255));
        healthInsuranceForm.setForeground(new java.awt.Color(255, 255, 255));
        healthInsuranceForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalDetails.setBackground(new java.awt.Color(255, 255, 255));

        headingPersonalDetails.setBackground(new java.awt.Color(255, 255, 255));
        headingPersonalDetails.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        headingPersonalDetails.setForeground(new java.awt.Color(0, 0, 0));
        headingPersonalDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingPersonalDetails.setText("Personal Details");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFocusable(true);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        firstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstNameLabel.setText("First Name:");

        firstNameTextbox.setBackground(new java.awt.Color(255, 255, 255));
        firstNameTextbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameTextboxFocusLost(evt);
            }
        });

        lastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastNameLabel.setText("Last Name:");

        lastNameTextbox.setBackground(new java.awt.Color(255, 255, 255));
        lastNameTextbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameTextboxFocusLost(evt);
            }
        });

        genderLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(0, 0, 0));
        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderLabel.setText("Gender:");

        genderButtonGroup.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        maleRadio.setForeground(new java.awt.Color(0, 0, 0));
        maleRadio.setText("Male");
        maleRadio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });

        genderButtonGroup.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        femaleRadio.setForeground(new java.awt.Color(0, 0, 0));
        femaleRadio.setText("Female");
        femaleRadio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        femaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioActionPerformed(evt);
            }
        });

        ageLabel.setBackground(new java.awt.Color(255, 255, 255));
        ageLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(0, 0, 0));
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("Age:");

        ageComboBox.setBackground(new java.awt.Color(255, 255, 255));
        ageComboBox.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        ageComboBox.setForeground(new java.awt.Color(0, 0, 0));
        ageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Under 35", "35 to 55 inclusive", "56 to 70 inclusive", "Over 70" }));
        ageComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personalDetailsLayout = new javax.swing.GroupLayout(personalDetails);
        personalDetails.setLayout(personalDetailsLayout);
        personalDetailsLayout.setHorizontalGroup(
            personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(headingPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(firstNameLabel)
                .addGap(89, 89, 89)
                .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lastNameLabel)
                .addGap(92, 92, 92)
                .addComponent(lastNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(genderLabel)
                .addGap(110, 110, 110)
                .addComponent(maleRadio)
                .addGap(16, 16, 16)
                .addComponent(femaleRadio))
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ageLabel)
                .addGap(132, 132, 132)
                .addComponent(ageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        personalDetailsLayout.setVerticalGroup(
            personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headingPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addGap(10, 10, 10)
                .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genderLabel))
                    .addComponent(femaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        healthInsuranceForm.add(personalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        schemaDetails.setBackground(new java.awt.Color(255, 255, 255));

        headingSchemaDetails.setBackground(new java.awt.Color(255, 255, 255));
        headingSchemaDetails.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        headingSchemaDetails.setForeground(new java.awt.Color(0, 0, 0));
        headingSchemaDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingSchemaDetails.setText("Schema Details");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFocusable(true);
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        policyTypeLabel.setBackground(new java.awt.Color(255, 255, 255));
        policyTypeLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        policyTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        policyTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        policyTypeLabel.setText("Policy Type:");

        policyTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        policyTypeComboBox.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        policyTypeComboBox.setForeground(new java.awt.Color(0, 0, 0));
        policyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Individual Policy", "Corporate Policy" }));
        policyTypeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        policyTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyTypeComboBoxActionPerformed(evt);
            }
        });

        hospitalCoverLabel.setBackground(new java.awt.Color(255, 255, 255));
        hospitalCoverLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        hospitalCoverLabel.setForeground(new java.awt.Color(0, 0, 0));
        hospitalCoverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalCoverLabel.setText("Hospital Cover:");

        hospitalCoverComboBox.setBackground(new java.awt.Color(255, 255, 255));
        hospitalCoverComboBox.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        hospitalCoverComboBox.setForeground(new java.awt.Color(0, 0, 0));
        hospitalCoverComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Public Hospital", "Private Hospital", "Comprehensive Hospital" }));
        hospitalCoverComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hospitalCoverComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalCoverComboBoxActionPerformed(evt);
            }
        });

        dayToDayExpensesLabel.setBackground(new java.awt.Color(255, 255, 255));
        dayToDayExpensesLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        dayToDayExpensesLabel.setForeground(new java.awt.Color(0, 0, 0));
        dayToDayExpensesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayToDayExpensesLabel.setText("Day to Day Expenses:");

        dayToDayExpensesComboBox.setBackground(new java.awt.Color(255, 255, 255));
        dayToDayExpensesComboBox.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        dayToDayExpensesComboBox.setForeground(new java.awt.Color(0, 0, 0));
        dayToDayExpensesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Standard", "Enhanced", "Comprehensive" }));
        dayToDayExpensesComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dayToDayExpensesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayToDayExpensesComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout schemaDetailsLayout = new javax.swing.GroupLayout(schemaDetails);
        schemaDetails.setLayout(schemaDetailsLayout);
        schemaDetailsLayout.setHorizontalGroup(
            schemaDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaDetailsLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(headingSchemaDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(schemaDetailsLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(schemaDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(policyTypeLabel)
                .addGap(86, 86, 86)
                .addComponent(policyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(schemaDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(hospitalCoverLabel)
                .addGap(66, 66, 66)
                .addComponent(hospitalCoverComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(schemaDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dayToDayExpensesLabel)
                .addGap(30, 30, 30)
                .addComponent(dayToDayExpensesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        schemaDetailsLayout.setVerticalGroup(
            schemaDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headingSchemaDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(schemaDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(policyTypeLabel))
                .addGap(10, 10, 10)
                .addGroup(schemaDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalCoverComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalCoverLabel))
                .addGap(10, 10, 10)
                .addGroup(schemaDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayToDayExpensesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayToDayExpensesLabel)))
        );

        healthInsuranceForm.add(schemaDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 350, -1));

        finalQuotation.setBackground(new java.awt.Color(255, 255, 255));

        headingFinalQuotation.setBackground(new java.awt.Color(255, 255, 255));
        headingFinalQuotation.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        headingFinalQuotation.setForeground(new java.awt.Color(0, 0, 0));
        headingFinalQuotation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingFinalQuotation.setText("Final Quotation");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setFocusable(true);
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        idNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        idNumberLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        idNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        idNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idNumberLabel.setText("ID Number:");

        displayIdNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        displayIdNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        displayIdNumberLabel.setText("0001");

        totalLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("Total:");

        displayTotalLabel.setBackground(new java.awt.Color(255, 255, 255));
        displayTotalLabel.setForeground(new java.awt.Color(0, 0, 0));

        finalButtons.setBackground(new java.awt.Color(255, 255, 255));

        calculateButton.setBackground(new java.awt.Color(255, 255, 255));
        calculateButton.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(0, 0, 0));
        calculateButton.setText("Calculate");
        calculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateButton.setRequestFocusEnabled(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        clearFormButton.setBackground(new java.awt.Color(255, 255, 255));
        clearFormButton.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        clearFormButton.setForeground(new java.awt.Color(0, 0, 0));
        clearFormButton.setText("Clear Form");
        clearFormButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearFormButton.setRequestFocusEnabled(false);
        clearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormButtonActionPerformed(evt);
            }
        });

        buyPolicyButton.setBackground(new java.awt.Color(255, 255, 255));
        buyPolicyButton.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        buyPolicyButton.setForeground(new java.awt.Color(0, 0, 0));
        buyPolicyButton.setText("Buy Policy");
        buyPolicyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyPolicyButton.setRequestFocusEnabled(false);
        buyPolicyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPolicyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout finalButtonsLayout = new javax.swing.GroupLayout(finalButtons);
        finalButtons.setLayout(finalButtonsLayout);
        finalButtonsLayout.setHorizontalGroup(
            finalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalButtonsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(clearFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(buyPolicyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        finalButtonsLayout.setVerticalGroup(
            finalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalButtonsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(finalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(clearFormButton)
                    .addComponent(buyPolicyButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout finalQuotationLayout = new javax.swing.GroupLayout(finalQuotation);
        finalQuotation.setLayout(finalQuotationLayout);
        finalQuotationLayout.setHorizontalGroup(
            finalQuotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(finalQuotationLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(headingFinalQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(finalQuotationLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(finalQuotationLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(idNumberLabel)
                .addGap(109, 109, 109)
                .addComponent(displayIdNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(finalQuotationLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalLabel)
                .addGap(145, 145, 145)
                .addComponent(displayTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        finalQuotationLayout.setVerticalGroup(
            finalQuotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalQuotationLayout.createSequentialGroup()
                .addComponent(finalButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(headingFinalQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(finalQuotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayIdNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(finalQuotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        healthInsuranceForm.add(finalQuotation, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, 170));

        healthDetails.setBackground(new java.awt.Color(255, 255, 255));

        healthlDetails.setBackground(new java.awt.Color(255, 255, 255));
        healthlDetails.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        healthlDetails.setForeground(new java.awt.Color(0, 0, 0));
        healthlDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthlDetails.setText("Health Details");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFocusable(true);
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        existingHealthConditionLabel.setBackground(new java.awt.Color(255, 255, 255));
        existingHealthConditionLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        existingHealthConditionLabel.setForeground(new java.awt.Color(0, 0, 0));
        existingHealthConditionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        existingHealthConditionLabel.setText("Existing Health Condition:");

        existingHealthConditionList.setBackground(new java.awt.Color(255, 255, 255));
        existingHealthConditionList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        existingHealthConditionList.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        existingHealthConditionList.setForeground(new java.awt.Color(0, 0, 0));
        existingHealthConditionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "None", "Bone Marrow and Immune System", "Cancer", "Cardiovascular disease", "Gastrointestinal", "Infections", "Kidneys", "Lungs", "Musculoskeletal" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        existingHealthConditionList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        existingHealthConditionList.setSelectedIndex(0);

        otherLabel.setBackground(new java.awt.Color(255, 255, 255));
        otherLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        otherLabel.setForeground(new java.awt.Color(0, 0, 0));
        otherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherLabel.setText("Other:");

        otherTextbox.setBackground(new java.awt.Color(255, 255, 255));
        otherTextbox.setColumns(10);
        otherTextbox.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        otherTextbox.setForeground(new java.awt.Color(0, 0, 0));
        otherTextbox.setRows(2);
        otherTextbox.setBorder(null);
        otherTextbox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                otherTextboxFocusLost(evt);
            }
        });
        otherScrollPane.setViewportView(otherTextbox);

        smokerLabel.setBackground(new java.awt.Color(255, 255, 255));
        smokerLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        smokerLabel.setForeground(new java.awt.Color(0, 0, 0));
        smokerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smokerLabel.setText("Smoker:");

        smokerButtonGroup.add(smokerRadio);
        smokerRadio.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        smokerRadio.setForeground(new java.awt.Color(0, 0, 0));
        smokerRadio.setText("Smoker");
        smokerRadio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        smokerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smokerRadioActionPerformed(evt);
            }
        });

        smokerButtonGroup.add(nonSmokerRadio);
        nonSmokerRadio.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        nonSmokerRadio.setForeground(new java.awt.Color(0, 0, 0));
        nonSmokerRadio.setText("Non-Smoker");
        nonSmokerRadio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nonSmokerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonSmokerRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout healthDetailsLayout = new javax.swing.GroupLayout(healthDetails);
        healthDetails.setLayout(healthDetailsLayout);
        healthDetailsLayout.setHorizontalGroup(
            healthDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthDetailsLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(healthlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(healthDetailsLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(healthDetailsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(existingHealthConditionLabel)
                .addGap(18, 18, 18)
                .addComponent(existingHealthConditionList))
            .addGroup(healthDetailsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(otherLabel)
                .addGap(140, 140, 140)
                .addComponent(otherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(healthDetailsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(smokerLabel)
                .addGap(149, 149, 149)
                .addComponent(smokerRadio)
                .addGap(10, 10, 10)
                .addComponent(nonSmokerRadio))
        );
        healthDetailsLayout.setVerticalGroup(
            healthDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(healthlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(healthDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingHealthConditionList)
                    .addComponent(existingHealthConditionLabel))
                .addGap(40, 40, 40)
                .addGroup(healthDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(healthDetailsLayout.createSequentialGroup()
                        .addComponent(otherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(healthDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(healthDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(smokerRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(smokerLabel))
                            .addComponent(nonSmokerRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(otherLabel)))
        );

        healthInsuranceForm.add(healthDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        background.add(healthInsuranceForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 1050, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormButtonActionPerformed
        clearFields();
        calculateButton.setEnabled(true);
        buyPolicyButton.setEnabled(false);
        clearFormButton.setEnabled(false);
    }//GEN-LAST:event_clearFormButtonActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        if (maleRadio.isSelected()) {
            gender = maleRadio.getText();
        }
    }//GEN-LAST:event_maleRadioActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed

        //Validate form
        validateForm();

        //If the form is properly completed calculate the total
        if (formValidated) {

            //Add selected existing health conditions to an array list
            existingHealthCondition = (ArrayList<String>) existingHealthConditionList.getSelectedValuesList();

            //Create Customer
            customer = new Customer(firstName, lastName, gender, age, smokerStatus, existingHealthCondition, other);

            //Set number format to currency  
            cf = NumberFormat.getCurrencyInstance();

            if (policyTypeComboBox.getSelectedItem().equals("Individual Policy")) {
                policy = new IndividualPolicy(policyType, hospitalCover, dayToDayExpenses, idNumber, formattedNumber);
                policy.setTotal(policy.calculatePremium(customer));
                //  display price on form with euro sign
                displayTotalLabel.setText(String.valueOf(cf.format(policy.getTotal())));
            } else if (policyTypeComboBox.getSelectedItem().equals("Corporate Policy")) {
                policy = new CorporatePolicy(policyType, hospitalCover, dayToDayExpenses, idNumber, formattedNumber);
                policy.setTotal(policy.calculatePremium(customer));
                //  display price on form with euro sign
                displayTotalLabel.setText(String.valueOf(cf.format(policy.getTotal())));
            }

            //  reset form validation 
            formValidated = false;

            clearFormButton.setEnabled(true);
            buyPolicyButton.setEnabled(true);
            calculateButton.setEnabled(false);

            //If age is over 70 disable the buy function and calculate button
            if (age.equals("Over 70")) {
                displayTotalLabel.setText(String.valueOf(cf.format(0)));
                clearFormButton.setEnabled(true);
                buyPolicyButton.setEnabled(false);
                calculateButton.setEnabled(true);

                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "No quotes given for over 70's",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        if (femaleRadio.isSelected()) {
            gender = femaleRadio.getText();
        }
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void buyPolicyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPolicyButtonActionPerformed
        //If buyPolicy button is pressed and age is not over 70 do the popup
        if (evt.getSource() == buyPolicyButton && !"Over 70".equals(age)) {
            BuyPolicyPopup popUp = new BuyPolicyPopup(customer, policy);
            popUp.setVisible(true);
        }
    }//GEN-LAST:event_buyPolicyButtonActionPerformed

    private void otherTextboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherTextboxFocusLost
        other = otherTextbox.getText();
    }//GEN-LAST:event_otherTextboxFocusLost

    private void firstNameTextboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextboxFocusLost
        firstName = firstNameTextbox.getText();
    }//GEN-LAST:event_firstNameTextboxFocusLost

    private void lastNameTextboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextboxFocusLost
        lastName = lastNameTextbox.getText();
    }//GEN-LAST:event_lastNameTextboxFocusLost

    private void smokerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smokerRadioActionPerformed
        if (smokerRadio.isSelected()) {
            smokerStatus = smokerRadio.getText();
        }
    }//GEN-LAST:event_smokerRadioActionPerformed

    private void nonSmokerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonSmokerRadioActionPerformed
        if (nonSmokerRadio.isSelected()) {
            smokerStatus = nonSmokerRadio.getText();
        }
    }//GEN-LAST:event_nonSmokerRadioActionPerformed

    private void ageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageComboBoxActionPerformed
        age = ageComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_ageComboBoxActionPerformed

    private void policyTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyTypeComboBoxActionPerformed
        policyType = policyTypeComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_policyTypeComboBoxActionPerformed

    private void hospitalCoverComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalCoverComboBoxActionPerformed
        hospitalCover = hospitalCoverComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_hospitalCoverComboBoxActionPerformed

    private void dayToDayExpensesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayToDayExpensesComboBoxActionPerformed
        dayToDayExpenses = dayToDayExpensesComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_dayToDayExpensesComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SláinteHealthInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SláinteHealthInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SláinteHealthInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SláinteHealthInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SláinteHealthInsurance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageComboBox;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JPanel background;
    private javax.swing.JButton buyPolicyButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearFormButton;
    private javax.swing.JComboBox<String> dayToDayExpensesComboBox;
    private javax.swing.JLabel dayToDayExpensesLabel;
    private javax.swing.JLabel displayIdNumberLabel;
    private javax.swing.JLabel displayTotalLabel;
    private javax.swing.JLabel existingHealthConditionLabel;
    private javax.swing.JList<String> existingHealthConditionList;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JPanel finalButtons;
    private javax.swing.JPanel finalQuotation;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextbox;
    private javax.swing.JLabel formHeading;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel headingFinalQuotation;
    private javax.swing.JLabel headingPersonalDetails;
    private javax.swing.JLabel headingSchemaDetails;
    private javax.swing.JPanel healthDetails;
    private javax.swing.JPanel healthInsuranceForm;
    private javax.swing.JLabel healthlDetails;
    private javax.swing.JComboBox<String> hospitalCoverComboBox;
    private javax.swing.JLabel hospitalCoverLabel;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextbox;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JRadioButton nonSmokerRadio;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JScrollPane otherScrollPane;
    private javax.swing.JTextArea otherTextbox;
    private javax.swing.JPanel personalDetails;
    private javax.swing.JComboBox<String> policyTypeComboBox;
    private javax.swing.JLabel policyTypeLabel;
    private javax.swing.JPanel schemaDetails;
    private javax.swing.ButtonGroup smokerButtonGroup;
    private javax.swing.JLabel smokerLabel;
    private javax.swing.JRadioButton smokerRadio;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
